### ISSUE TITLE
lc.exe

### ISSUE THREAD

**Issue by Navoichyk** [xavzen/KeyAuth-SellerAPI#3]
i know this is an error only i’m having, but when i try to compile i keep getting an error about lc.exe and how it can’t be found or something and i tried to look online but couldn’t find anything useful. how can i fix this?

**Comment by xavzen** [comment]
What version of visual studio are you trying to compile with?

**Comment by Navoichyk** [comment]
> What version of visual studio are you trying to compile with?

2022

**Comment by Navoichyk** [comment]
> > What version of visual studio are you trying to compile with?
> 
> 2022

if i exclude the license thing it builds with warnings but doesn’t open

**Comment by xavzen** [comment]
What license thing are you referring to?

**Comment by Navoichyk** [comment]
> What license thing are you referring to?

do you have a discord so i can dm you and show u?

**Comment by xavzen** [comment]
Sure you can add me @ xav#3433
